#:schema node_modules/wrangler/config-schema.json
name = "sublink-workeryw"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "63921b62ea3c4456a45fae3aa97d6307" }
]

[assets]
directory = "./public"
